name: tractian
description: "Tractian test"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  get: ^4.6.6
  logging: ^1.2.0
  dio: ^5.7.0
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.1
  get_storage: ^2.1.1
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/logo/